# Generated by Django 2.2.5 on 2019-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Indefinido')], default=3, verbose_name='Gênero'),
        ),
    ]
